"""empty message

Revision ID: ff4e96d3d8fa
Revises: 83990c0397e8
Create Date: 2022-08-02 15:39:09.317871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff4e96d3d8fa'
down_revision = '83990c0397e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('visits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'visits')
    # ### end Alembic commands ###
